POST http://localhost:8000/products
Content-Type: application/json

{
  "product_name": "Training Leash (Medium)",
  "price": 140,
  "stock": 10
}

### - Passed the test
GET http://localhost:8000/products/7
Content-Type: application/json

### - Passed the test
GET http://localhost:8000/products
Content-Type: application/json
Authorization: 6a9d71d5b5fdcc350aebf3af409dc23514d4f45525cd23eddd45b2ad9e015632

### - Passed the test
PUT http://localhost:8000/products/7
Content-Type: application/json

{
  "stock" : 100
}

### - Passed the test
DELETE http://localhost:8000/products/1
Content-Type: application/json

### - Passed the test
POST http://localhost:8000/users
Content-Type: application/json

{
  "full_name": "Admin Access",
  "email": "adminaccess@gmail.com",
  "role" : "admin",
  "password": "admin123",
  "address" : "Jl. Raya Kuta No. 1",
  "phone_number" : "081234567890",
  "pets" : [
    {
      "pet_name" : "Bobby",
      "type" : "Dog",
      "age" : 2,
      "breed" : "Golden Retriever"
    },
    {
      "pet_name" : "Kopi",
      "type" : "Dog",
      "age" : 1,
      "breed" : "Aspin mix breed"
    }
  ]
}

### - Passed the test
POST http://localhost:8000/users/pets
Content-Type: application/json

{
  "pet_name" : "Happy",
  "type" : "Cat",
  "age" : 2,
  "breed" : "Puspin",
  "owner_id" : 6
}

### - Passed the test
GET http://localhost:8000/users
Content-Type: application/json

### - Passed the test
PUT http://localhost:8000/users/41
Content-Type: application/json
Authorization: 6a9d71d5b5fdcc350aebf3af409dc23514d4f45525cd23eddd45b2ad9e015632

{
  "pets" : [
    {
      "pet_name" : "Happy",
      "type" : "Cat",
      "age" : 2,
      "breed" : "Puspin",
      "gender" : "male"
    }
  ]
}

### - Passed the test
POST http://localhost:8000/orders
Content-Type: application/json

{
  "status": "pending",
  "customer_id": 6,
  "total_price": 140,
  "quantity": 1,
  "product_items_link" : [
    {
      "product_id" : 7,
      "quantity" : 5
    }
  ]
}

### - Passed the test
DELETE http://localhost:8000/users/7

# ------------------------ ORDER API ------------------------

### - Passed the test
PUT http://localhost:8000/orders/status/5
Content-Type: application/json

{
  "status": "confirmed"
}

### - Passed the test
PUT http://localhost:8000/orders/12
Content-Type: application/json

{
  "product_items_link" : [
    {
      "product_id" : 7,
      "quantity" : 1
    }
  ]
}

### - Passed the test
PUT http://localhost:8000/orders/cancel/5
Content-Type: application/json

### - Passed the test
GET http://localhost:8000/orders/6
Content-Type: application/json

### - Passed the test
GET http://localhost:8000/orders
Content-Type: application/json
Authorization: 6a9d71d5b5fdcc350aebf3af409dc23514d4f45525cd23eddd45b2ad9e015632

### - Passed the test
DELETE http://localhost:8000/orders/?list=7&list=8
Content-Type: application/json

# ------------------------ BOOKING API ------------------------

### - Passed the test
POST http://localhost:8000/booking
Content-Type: application/json
Authorization: 123123132

{
  "status": "pending",
  "customer_id": 6,
  "total_price": 140,
  "service_id": 1,
  "reserved_day" : "2024-07-23",
  "reserved_time" : "10:00:00",
  "booking_items_link" : [
    {
      "pet_id" : 5
    },
    {
      "pet_id" : 4
    }
  ]  
}

### - Passed the test
POST http://localhost:8000/booking/services
Content-Type: application/json

{
  "service_name" : "Deworming (<10kg)",
  "price" : 250,
  "duration" : 1
}

### - Passed the test
GET http://localhost:8000/booking
Content-Type: application/json
Authorization: 6a9d71d5b5fdcc350aebf3af409dc23514d4f45525cd23eddd45b2ad9e015632

### - Passed the test
GET http://localhost:8000/booking/user/6?range=week

### - Passed the test
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "adminaccess@gmail.com",
  "password": "admin123"
}

### - Passed the test
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "full_name": "Kairus Tecson",
  "email": "kairustecsonpersonal@gmail.com",
  "password": "kairus123",
  "address" : "Jl. Raya Kuta No. 1",
  "phone_number" : "09234567890",
  "role" : "basic",
  "pets" : [
    {
      "pet_name" : "Bobby",
      "type" : "Dog",
      "age" : 2,
      "breed" : "Golden Retriever"
    }
  ]
}

### - Passed the test
GET http://localhost:8000/booking/services
Content-Type: application/json
Authorization: 6a9d71d5b5fdcc350aebf3af409dc23514d4f45525cd23eddd45b2ad9e015632