"""added gender column in pets

Revision ID: 28c164334170
Revises: 6ba0bb5107f3
Create Date: 2024-07-23 20:07:56.926717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28c164334170'
down_revision: Union[str, None] = '6ba0bb5107f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    petsgender = sqlmodel.Enum("FEMALE", "MALE", name="petsgender")
    petsgender.create(op.get_bind(), checkfirst=True)
    op.add_column('pets', sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='petsgender'), nullable=False, server_default="MALE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'gender')
    # ### end Alembic commands ###
