"""fixed booking table

Revision ID: 5cec7c3b1954
Revises: 34fc99a8dfbe
Create Date: 2024-07-19 06:00:18.574521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5cec7c3b1954'
down_revision: Union[str, None] = '34fc99a8dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'date_and_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date_and_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
