"""added gcash data in order table

Revision ID: acd0b2c8c309
Revises: 7708abd1a3a4
Create Date: 2024-08-09 11:33:47.045061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'acd0b2c8c309'
down_revision: Union[str, None] = '7708abd1a3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gcash_reference_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('gcash_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'gcash_number')
    op.drop_column('orders', 'gcash_reference_number')
    # ### end Alembic commands ###
