"""set not nullable to all date attributes

Revision ID: b4971f3a9928
Revises: c160b2353779
Create Date: 2024-07-22 11:29:01.600419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4971f3a9928'
down_revision: Union[str, None] = 'c160b2353779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'reserved_date')
    op.drop_column('orders', 'order_date')
    op.drop_column('products', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_updated')
    op.add_column('products', sa.Column('last_updated', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('orders', 'order_date')
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('booking', 'reserved_date')
    op.add_column('booking', sa.Column('reserved_date', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
