"""added quantity to order product link table

Revision ID: c160b2353779
Revises: 7844c4b857e2
Create Date: 2024-07-22 04:36:33.784958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c160b2353779'
down_revision: Union[str, None] = '7844c4b857e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderproductassociation', sa.Column('quantity', sa.Integer(), nullable=True, server_default='1'))
    op.alter_column('orderproductassociation', 'quantity', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderproductassociation', 'quantity')
    # ### end Alembic commands ###
